blogging/urls.py
from django.conf.urls import patterns, include, url
import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'blogging.views.home', name='home'),
    url(r'^blogs/', include('blogs.urls' , namespace="blogs")),
    url(r'^archive/', include('blogs.urls' , namespace="archive")),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^Images/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

blogs/urls.py
from django.conf.urls import patterns, url
from blogs.views import PostYearArchiveView, PostMonthArchiveView

from blogs import views

urlpatterns = patterns('',
    url(r'^$', 'blogs.views.listing', name = 'index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name = 'detail'),
    url(r'^archive/(?P<year>\d{4})/$',views.PostYearArchiveView.as_view(), name = 'post_year_archive'),
    url(r'^archive/(?P<year>\d{4})/(?P<month>[-\w]+)/$',views.PostMonthArchiveView.as_view(), name = 'post_month_archive'),
)

testtinymce/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 
    #    'django.views.static.serve', {"document_root": settings.MEDIA_ROOT}),
)
urlpatterns += staticfiles_urlpatterns()

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

blogs/models.py
import datetime, markdown
from django.db import models
from django.utils import timezone


class Post(models.Model):
    post_title = models.CharField(max_length=200)
    post_text = models.TextField()
    pub_date = models.DateTimeField('date published', default=timezone.now)
    is_active = models.BooleanField()
    
    def __unicode__(self):
        return self.post_title
        
    @property
    def post_html(self):
        return markdown.markdown(self.post_text)
        
    class Meta:
        ordering = ['pub_date']


class Image(models.Model):
    post = models.ForeignKey(Post, related_name="images")
    image = models.ImageField(upload_to='Images')
    image_title = models.CharField(max_length=100, blank=True)

blogs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.dates import YearArchiveView, MonthArchiveView

from blogs.models import Post
        
        
class DetailView(generic.DetailView):
    model = Post
    template_name = 'blogs/detail.html'
    
    
def listing(request):
    post_list = Post.objects.filter(is_active=True).order_by('pub_date').reverse()
    paginator = Paginator(post_list, 5)

    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blogs/index.html', {"posts": posts})
    
    
class PostYearArchiveView(YearArchiveView):
    queryset = Post.objects.filter(is_active=True).order_by('pub_date')
    date_field = "pub_date"
    make_object_list = True
    allow_future = True

 
class PostMonthArchiveView(MonthArchiveView):
    queryset = Post.objects.filter(is_active=True).order_by('pub_date').reverse()
    date_field = "pub_date"
    make_object_list = True

    
    
    

templates/blogs/base.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    
    <head>
        <title> {% block pagetitel %} Pagename {% endblock %} </title>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    </head>
    
    <body>
        

        <link rel="stylesheet" type="text/css" href="{% static 'blogs/style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'blogs/foundation.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'blogs/foundation.min.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'blogs/normalize.css' %}" />
        
        <div class="row">
            <div class="haupttitel">
                <div class="large-12 columns">
                {% block titel %}
                    sometitle
                {% endblock %}
                </div>
                <hr>
            </div>
        </div>
        <br>
        
        <div class="row"> 
            <div class="large-7 columns">
                <div class="row">
                    <div class="large-12 columns">
                        {% block content %} 
                            upper content left from sidebar
                        {% endblock %}
                    </div>
                    <hr>
                </div>
                <div class="row">
                    <div class="sub">
                        {% block subtitel %}
                        untertitel
                        {% endblock %}
                    </div>
                </div>
                <div class="row">
                    <div class="large-12 large-uncentered columns">
                    {% block low%}
                    abhängig von untertitel
                    {% endblock %}
                </div>
            </div>
        </div>
        
        <div class="large-4 large-offset-1 columns">
            <div class="row">
                <div class="sidebar large-12 columns">{% block sidetitel %}<h3>Archive</h3>{% endblock %}
                    {% block sidebar %}
                        sidebar displayed left from content
                    {% endblock %}
                </div>
            </div>
        </div>
       <hr> 
    </div>

    <div class="row">
        <div class="large-12 large-centered columns">
        {% block bottom %}
            some side scroll or back to ... page stuff
        {% endblock %}
        </div>
    </div>   
    </body>
</html>
     

templates/blogs/detail.html
{% extends "base.html" %}
{% load blog_tags %}

{% block pagetitel %}
    {{ post.post_title }}
{% endblock %}
    
{% block titel %}
   <h1>{{ post.post_title }}</h1>
{% endblock %}

{% block content %}
    <br />
    <p>{{ post.post_text|md_to_html|safe}}</p><br />
{% endblock %}

{% block subtitel %}
    <p>Bilder</p><br />
{% endblock %}

{% block low %}
    {% for image in post.images.all %}
        <li>
        <a class="pics" rel="gallery" href='{{ image.image.url }}'><img src="{{ image.image.url }}" title="{{ image.image_title }}" 
        alt="" width="200" height="100" />{{ image.image_title }}</a>
        </li>
    {% endfor %}
    <br />
{% endblock %}

{% block bottom %}
    <div class="back">
        <a href ={% url 'blogs:index'%}>back to main page</a>
        {% if error_message %}
            <p><strong>{{ error_message }}</strong></p>
        {% endif %}
    </div>
{% endblock %}
     

templates/blogs/index.html
{% extends "base.html" %}

{% block pagetitel %}
    Lamins Blogpage
{% endblock %}

{% block titel %}
    <h2>Lamins Blog</h2>
{% endblock %}

{% block content %} 
    <br /><p>Herzlich willkommen auf meiner Blogseite.<br />
    Hier finden Sie ...<br />.....<br />.....<br />.....<br />.....<br />.....<br />.....<br />.....<br />
    viel Spass beim stöbern...</p>
{%endblock%}

{% block subtitel %}
    <h3>Blogbeiträge:</h3>
{% endblock %}

{% block low%}
    {% if posts %}
        <ul>
        {% for post in posts %}
            {% if post.is_active %}
                <li>
                    <a href = "{% url 'blogs:detail' post.id %}">
                    <em>{{ post.pub_date|date:"d.m.y - H:i" }}</em> 
                    <p><strong>{{ post.post_title }}</strong></p></a>
                </li>
            {% endif %}
        {% endfor %}
        </ul>
    {% else %}
        <p>No posts are available.</p>
    {% endif %}
{% endblock %}

{% block sidetitel %}
    <h3>Archive</h3>
{% endblock %}
<hr>
{% block bottom %}
    <div class="pagination">
        <span class="step-links">
            {% if posts.has_previous %}
                <a href="?page={{ posts.previous_page_number }}">&lt;&lt;&lt;previous</a>
            {% endif %}

            <span class="current">
                Page {{ posts.number }} of {{ posts.paginator.num_pages }}
            </span>

            {% if posts.has_next %}
                <a href="?page={{ posts.next_page_number }}">next&gt;&gt;&gt;</a>
            {% endif %}
        </span>
    </div>
{% endblock %}   

templates/blogs/post_archive_month.html
{% extends "base.html" %}

{% block pagetitel %}
    All Posts for {{ month|date:"F - Y" }}
{% endblock %}

{% block titel %}
    <h1>All Posts for {{ month|date:"F - Y" }}</h1>
{% endblock %}

{% block content%}

{% endblock %}

{% block subtitel %}
    <h3>Blogbeiträge:</h3>
{% endblock %}

{% block low %}
    {% for obj in object_list %}        
            <a href = "{% url 'blogs:detail' obj.id %}">{{ obj.pub_date|date:"d.m - H:i" }} - <p><strong>{{ obj.post_title }}</strong></p></a>       
    {% endfor %}
{% endblock %}
    
{% block bottom %}
    <div class="back">
        <a href ={% url 'blogs:index'%}>back to main page</a>
    </div>
{% endblock %}

templates/blogs/post_archive_year.html
{% extends "base.html" %}

{% block pagetitel %}
    All Posts for {{ year|date:"Y" }}
{% endblock %}

{% block titel %}
    <h1>All Posts for {{ year|date:"Y" }}</h1>
{% endblock %}

{% block content%}

{% endblock %}

{% block subtitel %}
    <h3>Blogbeiträge:</h3>
{% endblock %}

{% block low %}
    {% for obj in object_list %}
        <br />
            <a href = "{% url 'blogs:detail' obj.id %}">{{ obj.pub_date|date:"d.m.y - H:i" }} - <p><strong>{{ obj.post_title }}</strong></p></a>       
    {% endfor %}
{% endblock %}
    
{% block bottom %}
    <div class="back">
        <a href ={% url 'blogs:index'%}>back to main page</a>
    </div>
{% endblock %}

templates/blogs/post_year_archive.html
<ul>
    {% for date in date_list %}
        <li>{{ date|date }}</li>
    {% endfor %}
</ul>

<div>
    <h1>All Posts for {{ year|date:"Y" }}</h1>
    {% for obj in object_list %}
        <p>
            {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }}
        </p>
    {% endfor %}
</div>

templates/blogs/results.html
<h1>{{ blog.blog_text }}</h1>

<ul>
{% for comment in blog.comment_set.all %}
    <li>{{ comment.comment_text }} -- {{ comment.likes }} likes {{ comment.likes|pluralize}}</li>
{% endfor %}
</ul>

<a href = "{% url 'blogs:detail' blog.id %}">Like again?</a>